version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/attendance_db
      JDBC_DATABASE_USERNAME: admin
      JDBC_DATABASE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

  admin-panel:
    build: ./admin-panel
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  entity-dashboard:
    build: ./entity-dashboard
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    ports:
      - "3001:3000"
    command: ["npm", "start"]
volumes:
  db_data:
