# Organization Service Configuration
spring:
  application:
    name: organization-service
  
  # Database Configuration
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://ams-postgres-microservices:5432/attendance_db}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Kolkata

# Server Configuration
server:
  port: ${SERVER_PORT:8082}
  address: 0.0.0.0
  servlet:
    context-path: /organization

# gRPC Configuration
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9092}
    address: 0.0.0.0
  client:
    GLOBAL:
      negotiation-type: plaintext
    user-service:
      address: 'static://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_GRPC_PORT:9093}'
      negotiation-type: plaintext
    auth-service:
      address: 'static://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_GRPC_PORT:9091}'
      negotiation-type: plaintext
    attendance-service:
      address: 'static://${ATTENDANCE_SERVICE_HOST:localhost}:${ATTENDANCE_SERVICE_GRPC_PORT:9094}'
      negotiation-type: plaintext

# Service Discovery Configuration
service:
  discovery:
    enabled: ${SERVICE_DISCOVERY_ENABLED:true}
    service-name: organization-service
    service-type: _grpc._tcp.local.
    port: ${grpc.server.port}
    domain: local.
    ttl: 120
    auto-register: true

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# Logging Configuration
logging:
  level:
    com.example.attendancesystem.organization: ${LOG_LEVEL:DEBUG}
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/organization-service.log
    max-size: 10MB
    max-history: 30

# Custom Application Properties
app:
  name: "Organization Service"
  version: "1.0.0"
  description: "Organization Management Microservice"
